-- Tables -------------------------------------------------------
-- --------------------------------------------------------------

CREATE TABLE NEN_TYPE (
    ID_NEN_TYPE NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(255)
);

CREATE TABLE HUNTER (
    ID_HUNTER NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER,
    ORIGIN VARCHAR2(100)
);

CREATE TABLE HUNTER_NEN (
    ID_HUNTER NUMBER NOT NULL,
    ID_NEN_TYPE NUMBER NOT NULL,
    PERCENTAGE FLOAT,
    PRIMARY KEY (ID_HUNTER, ID_NEN_TYPE),
    CONSTRAINT FK_HUNTER FOREIGN KEY (ID_HUNTER) REFERENCES HUNTER(ID_HUNTER),
    CONSTRAINT FK_NEN_TYPE FOREIGN KEY (ID_NEN_TYPE) REFERENCES NEN_TYPE(ID_NEN_TYPE)
);

-- Data ---------------------------------------------------------
-- --------------------------------------------------------------

INSERT INTO NEN_TYPE (NAME, DESCRIPTION) VALUES ('Intensificación', 'Mejora sus habilidades físicas');
INSERT INTO NEN_TYPE (NAME, DESCRIPTION) VALUES ('Transformación', 'Cambia propiedades de su aura');
INSERT INTO NEN_TYPE (NAME, DESCRIPTION) VALUES ('Materialización', 'Crea objetos físicos');
INSERT INTO NEN_TYPE (NAME, DESCRIPTION) VALUES ('Especialización', 'Habilidades únicas fuera de las demás categorías');
INSERT INTO NEN_TYPE (NAME, DESCRIPTION) VALUES ('Emisión', 'Proyecta el aura lejos del cuerpo');
INSERT INTO NEN_TYPE (NAME, DESCRIPTION) VALUES ('Manipulación', 'Controla objetos o seres');

INSERT INTO HUNTER (NAME, AGE, ORIGIN) VALUES ('Gon Freecss', 14, 'Isla Ballena');
INSERT INTO HUNTER (NAME, AGE, ORIGIN) VALUES ('Killua Zoldyck', 14, 'Familia Zoldyck');
INSERT INTO HUNTER (NAME, AGE, ORIGIN) VALUES ('Kurapika', 17, 'Kurta Clan');
INSERT INTO HUNTER (NAME, AGE, ORIGIN) VALUES ('Leorio Paradinight', 19, 'Ciudad desconocida');

INSERT INTO HUNTER_NEN VALUES (1, 1, 90.0);
INSERT INTO HUNTER_NEN VALUES (2, 2, 80.5);
INSERT INTO HUNTER_NEN VALUES (3, 4, 95.0);
INSERT INTO HUNTER_NEN VALUES (4, 5, 65.0);

-- Stored Procedure ---------------------------------------------
-- --------------------------------------------------------------

-- Query --------------------------------------------------------
-- --------------------------------------------------------------

SELECT
    a.id_hunter,
    a.name,
    a.age,
    a.origin,
    b.percentage,
    c.name
FROM hunter a 
    INNER JOIN hunter_nen b ON a.id_hunter = b.id_hunter
    INNER JOIN nen_type c ON c.id_nen_type = b.id_nen_type;

DROP TABLE HUNTER_NEN;
DROP TABLE HUNTER;
DROP TABLE NEN_TYPE;

-- --------------------------------------------------------------
-- --------------------------------------------------------------